#wordpress-service
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: NodePort
  selector:
   app: wordpress
  ports:
    - port: 8000
      targetPort: 80
      nodePort: 30080
---
#wordpress-service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  selector:
   app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30081
---
#mysql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: sequel
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_USER
          value: saileshp56
        - name: MYSQL_PASSWORD
          value: my_password
        - name: MYSQL_ROOT_HOST
          value: "%"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
#wordpress
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service:3306
        - name: WORDPRESS_DB_USER
          value: saileshp56
        - name: WORDPRESS_DB_PASSWORD
          value: my_password
        - name: WORDPRESS_DB_NAME
          value: sequel
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
---
#wordpress pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
#mysql pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
